<template><div><div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token comment">//登录API</span>
<span class="token keyword">public</span> <span class="token keyword">function</span> <span class="token function-definition function">login</span><span class="token punctuation">(</span><span class="token class-name type-declaration">Request</span> <span class="token variable">$request</span><span class="token punctuation">)</span>
    <span class="token punctuation">{</span>
    <span class="token variable">$username</span> <span class="token operator">=</span> <span class="token variable">$request</span><span class="token operator">-></span><span class="token function">param</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'login_act'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token variable">$password</span> <span class="token operator">=</span> <span class="token variable">$request</span><span class="token operator">-></span><span class="token function">param</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'login_pwd'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token variable">$info</span> <span class="token operator">=</span> <span class="token class-name static-context">UserModel</span><span class="token operator">::</span><span class="token function">where</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'login_act'</span><span class="token punctuation">,</span><span class="token variable">$username</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">find</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span><span class="token variable">$info</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">create</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span><span class="token string single-quoted-string">'用户不存在'</span><span class="token punctuation">,</span><span class="token number">401</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token variable">$info</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'login_pwd'</span><span class="token punctuation">]</span><span class="token operator">!=</span><span class="token function">md5</span><span class="token punctuation">(</span><span class="token variable">$password</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token variable">$this</span><span class="token operator">-></span><span class="token function">create</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span><span class="token string single-quoted-string">'账号或密码错误'</span><span class="token punctuation">,</span><span class="token number">401</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token variable">$key</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'api123456'</span><span class="token punctuation">;</span>
        <span class="token variable">$payload</span><span class="token operator">=</span><span class="token punctuation">[</span>
            <span class="token string single-quoted-string">'iss'</span><span class="token operator">=></span><span class="token string double-quoted-string">"http://www.api.io"</span><span class="token punctuation">,</span>
            <span class="token string single-quoted-string">'aud'</span><span class="token operator">=></span><span class="token string double-quoted-string">"http://www.api.io"</span><span class="token punctuation">,</span>
            <span class="token string single-quoted-string">'iat'</span><span class="token operator">=></span><span class="token function">time</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
            <span class="token string single-quoted-string">'nbf'</span><span class="token operator">=></span><span class="token function">time</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
            <span class="token string single-quoted-string">'aid'</span><span class="token operator">=></span><span class="token variable">$info</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'id'</span><span class="token punctuation">]</span>
        <span class="token punctuation">]</span><span class="token punctuation">;</span>
        <span class="token variable">$token</span> <span class="token operator">=</span> <span class="token class-name static-context">JWT</span><span class="token operator">::</span><span class="token function">encode</span><span class="token punctuation">(</span><span class="token variable">$payload</span><span class="token punctuation">,</span> <span class="token variable">$key</span><span class="token punctuation">,</span><span class="token string double-quoted-string">"HS256"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span> <span class="token function">json</span><span class="token punctuation">(</span><span class="token punctuation">[</span>
            <span class="token string single-quoted-string">'data'</span><span class="token operator">=></span><span class="token variable">$info</span><span class="token punctuation">,</span>
            <span class="token string single-quoted-string">'msg'</span><span class="token operator">=></span><span class="token string single-quoted-string">'登录成功！'</span><span class="token punctuation">,</span>
            <span class="token string single-quoted-string">'code'</span><span class="token operator">=></span><span class="token number">200</span><span class="token punctuation">,</span>
            <span class="token string single-quoted-string">'token'</span><span class="token operator">=></span><span class="token variable">$token</span>
        <span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


