<template><div><div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code>在 config 目录下的 log<span class="token operator">.</span>php 配置文件，用于设置日志信息；
系统提供了不同日志级别，默认 info 级别，从低到高排列如下：
debug<span class="token operator">/</span>info<span class="token operator">/</span>notice<span class="token operator">/</span>warning<span class="token operator">/</span>error<span class="token operator">/</span>critical<span class="token operator">/</span>alert<span class="token operator">/</span>emergency<span class="token operator">/</span>sql；
使用 <span class="token function">record</span><span class="token punctuation">(</span><span class="token punctuation">)</span>方法，记录一条测试日志；
<span class="token class-name static-context">Log</span><span class="token operator">::</span><span class="token function">record</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'测试日志！'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token function">record</span><span class="token punctuation">(</span><span class="token punctuation">)</span>方法不是实时记录，需要等待程序完毕后决定是否写入日志；
如果在写入方法后添加 <span class="token function">close</span><span class="token punctuation">(</span><span class="token punctuation">)</span>关闭写入，那么 <span class="token function">record</span><span class="token punctuation">(</span><span class="token punctuation">)</span>方法则不写入；
<span class="token class-name static-context">Log</span><span class="token operator">::</span><span class="token function">close</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
系统还提供了一个 <span class="token function">write</span><span class="token punctuation">(</span><span class="token punctuation">)</span>方法，进行时时写入，不理会其它限制；
<span class="token class-name static-context">Log</span><span class="token operator">::</span><span class="token function">write</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'测试日志信息'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'error'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
 系统发生异常后，会自动写入 error 日志，如果你想手动也可以；
<span class="token keyword">try</span> <span class="token punctuation">{</span>
<span class="token keyword">echo</span> <span class="token number">0</span><span class="token operator">/</span><span class="token number">0</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span><span class="token class-name">ErrorException</span> <span class="token variable">$e</span><span class="token punctuation">)</span>
<span class="token punctuation">{</span>
<span class="token keyword">echo</span> <span class="token string single-quoted-string">'发生错误：'</span><span class="token operator">.</span><span class="token variable">$e</span><span class="token operator">-></span><span class="token function">getMessage</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token class-name static-context">Log</span><span class="token operator">::</span><span class="token function">record</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'被除数不得为零'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'error'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


