<template><div><p>定义路由</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token keyword">use</span> <span class="token package">think<span class="token punctuation">\</span>facade<span class="token punctuation">\</span>Route</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>&amp;&amp;
注册路由</p>
<p>传统写法</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token class-name static-context">Route</span><span class="token operator">::</span><span class="token function">rule</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'路由表达式'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'路由地址'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'请求类型'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token class-name static-context">Route</span><span class="token operator">::</span><span class="token function">rule</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'new/:id'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'News/update'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'POST'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>快捷注册方法</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token class-name static-context">Route</span><span class="token operator">::</span>快捷方法名<span class="token punctuation">(</span><span class="token string single-quoted-string">'路由表达式'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'路由地址'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

例如：
<span class="token class-name static-context">Route</span><span class="token operator">::</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'new/&lt;id>'</span><span class="token punctuation">,</span><span class="token string single-quoted-string">'News/read'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 定义GET请求路由规则</span>
<span class="token class-name static-context">Route</span><span class="token operator">::</span><span class="token function">post</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'new/&lt;id>'</span><span class="token punctuation">,</span><span class="token string single-quoted-string">'News/update'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 定义POST请求路由规则</span>
<span class="token class-name static-context">Route</span><span class="token operator">::</span><span class="token function">put</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'new/&lt;id>'</span><span class="token punctuation">,</span><span class="token string single-quoted-string">'News/update'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 定义PUT请求路由规则</span>
<span class="token class-name static-context">Route</span><span class="token operator">::</span><span class="token function">delete</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'new/&lt;id>'</span><span class="token punctuation">,</span><span class="token string single-quoted-string">'News/delete'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 定义DELETE请求路由规则</span>
<span class="token class-name static-context">Route</span><span class="token operator">::</span><span class="token function">any</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'new/&lt;id>'</span><span class="token punctuation">,</span><span class="token string single-quoted-string">'News/read'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 所有请求都支持的路由规则</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


