<template><div><p>#图像处理</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code>composer <span class="token keyword">require</span> topthink<span class="token operator">/</span>think<span class="token operator">-</span>image
引入进来之后，首先创建图像处理对象；

<span class="token variable">$image</span> <span class="token operator">=</span> <span class="token class-name static-context">Image</span><span class="token operator">::</span><span class="token function">open</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'image.png'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//图片宽度</span>
<span class="token keyword">echo</span> <span class="token variable">$image</span><span class="token operator">-></span><span class="token function">width</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//图片高度</span>
<span class="token keyword">echo</span> <span class="token variable">$image</span><span class="token operator">-></span><span class="token function">height</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//图片类型</span>
<span class="token keyword">echo</span> <span class="token variable">$image</span><span class="token operator">-></span><span class="token function">type</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//图片 mime</span>
<span class="token keyword">echo</span> <span class="token variable">$image</span><span class="token operator">-></span><span class="token function">mime</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//图片大小</span>
<span class="token function">dump</span><span class="token punctuation">(</span><span class="token variable">$image</span><span class="token operator">-></span><span class="token function">size</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">#使用 crop()方法可以裁剪图片，并使用 save()方法保存到指定路径；</span>
使用 <span class="token function">thumb</span><span class="token punctuation">(</span><span class="token punctuation">)</span>方法，可以生成缩略图，配合 <span class="token function">save</span><span class="token punctuation">(</span><span class="token punctuation">)</span>把缩略图保存下来；

<span class="token comment">//裁剪图片</span>
<span class="token variable">$image</span><span class="token operator">-></span><span class="token function">crop</span><span class="token punctuation">(</span><span class="token number">550</span><span class="token punctuation">,</span><span class="token number">400</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">save</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'crop1.png'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//生成缩略图</span>
<span class="token variable">$image</span><span class="token operator">-></span><span class="token function">thumb</span><span class="token punctuation">(</span><span class="token number">500</span><span class="token punctuation">,</span><span class="token number">500</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">save</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'thumb1.png'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

使用 <span class="token function">rotate</span><span class="token punctuation">(</span><span class="token punctuation">)</span>方法，可以旋转图片，默认是 <span class="token number">90</span> 度，参数可以设置；
<span class="token variable">$image</span><span class="token operator">-></span><span class="token function">rotate</span><span class="token punctuation">(</span><span class="token number">180</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">save</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'rotate1.png'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token number">11.</span> <span class="token function">save</span><span class="token punctuation">(</span><span class="token punctuation">)</span>方法可以配置的参数除了保存文件名的路径，还有以下几个：
<span class="token number">12.</span> <span class="token function">save</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'路径'</span><span class="token punctuation">,</span><span class="token punctuation">[</span><span class="token string single-quoted-string">'类型'</span><span class="token punctuation">,</span><span class="token string single-quoted-string">'质量'</span><span class="token punctuation">,</span><span class="token string single-quoted-string">'是否隔行扫描'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>，追踪到方法查看；
<span class="token function">save</span><span class="token punctuation">(</span><span class="token variable">$pathname</span><span class="token punctuation">,</span> <span class="token variable">$type</span> <span class="token operator">=</span> <span class="token constant">null</span><span class="token punctuation">,</span> <span class="token variable">$quality</span> <span class="token operator">=</span> <span class="token number">80</span><span class="token punctuation">,</span> <span class="token variable">$interlace</span> <span class="token operator">=</span> <span class="token constant boolean">true</span><span class="token punctuation">)</span>
<span class="token number">13.</span> <span class="token function">water</span><span class="token punctuation">(</span><span class="token punctuation">)</span>方法，可以给图片增加一个图片水印，默认位置为右下角，可看源码常量；
<span class="token variable">$image</span><span class="token operator">-></span><span class="token function">water</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'mr.lee.png'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">save</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'water1.png'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token number">14.</span> <span class="token function">text</span><span class="token punctuation">(</span><span class="token punctuation">)</span>方法，可以给图片增加一个文字水印，具体如下：
<span class="token variable">$image</span><span class="token operator">-></span><span class="token function">text</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'Mr.Lee'</span><span class="token punctuation">,</span><span class="token function">getcwd</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">.</span><span class="token string single-quoted-string">'/1.ttf'</span><span class="token punctuation">,</span><span class="token number">20</span><span class="token punctuation">,</span><span class="token string single-quoted-string">'#ffffff'</span><span class="token punctuation">)</span><span class="token operator">-></span><span class="token function">save</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'text1.png'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


